
name: Buil and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm deps
      run: npm install
    - name: Run appl unit test
      run: npm run test:unit
    - name: Display sofuni user
      run: echo user

  
  deploy:
    needs:  build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: wai 120 sec
        run: sleep 120    
  run-ui--test:

    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm deps
      run: npm install
    - name: Run appl unit test
      run: npm run test:ui
    - name: Display sofuni user
      run: echo user
    - name: Dsolay softuniu
      run:  echo "Delo"